### ISSUE TITLE
SCAuth gives "Authentication Succeeded," without doing anything else

### ISSUE THREAD

**Issue by josibake** [randyzwitch/RSiteCatalyst#131]
After entering my credentials, SCAuth claims that "Authentication Succeeded" but does not create anything in my environment.  I also played around with changing the company name and shared secret and it claims "Authentication Succeeded"  regardless of what I put in.

**Comment by randyzwitch** [comment]
Yeah, that message has always been misleading. It should just say "Credentials Saved", it doesn't actually validate that your credentials are correct. Or, I should just actually test the credentials with an API call.

**Comment by josibake** [comment]
I think the problem I am having is that it is not saving credentials at all in the work environment.  SCAuth runs, but nothing appears to happen.

**Comment by randyzwitch** [comment]
That is by design. Per CRAN rules, I was forced to change the design of the package not to write to the global workspace. So when you run `SCAuth()`, your credentials are saved in the RSiteCatalyst namespace, not the global namespace. So other than the misleading 'Authentication Succeeded' message, you won't see any other hints that your credentials are saved.

Have you tried any simple calls like the following:

```R
SCAuth("user:company", "shared secret")
report_suites <- GetReportSuites()
```

This will quickly let you know if things are working or not, by returning a data frame with the report suites in your company account.

**Comment by josibake** [comment]
I see!  I was going off the old youtube video on your site and getting really confused.  That makes sense, though.  It looks like everything is working now.  Thank you for all your work!  I am really excited to start using this.

**Comment by randyzwitch** [comment]
Thanks for that feedback about the video. So many things have changed, I should probably create a new one.
