### ISSUE TITLE
GetUsageLog function in docs but not in package?

### ISSUE THREAD

**Issue by beskelton** [randyzwitch/RSiteCatalyst#163]
I was trying some of your admin related functions, and was able to use GetLogins() - thanks! - but when I tried GetUsageLog I received an error.

usagelog <- GetUsageLog("2016-03-01","2016-03-31")
Error: could not find function "GetUsageLog"

I found the function in your docs, which is what led me to try it. https://github.com/randyzwitch/RSiteCatalyst/blob/master/R/GetUsageLog.R

However, the function is not listed in 1.4.8 CRAN version package I installed in RStudio. I also tried to install the devtools version, but same result. GetLogins is present, but GetUsageLog is not.

**Comment by randyzwitch** [comment]
Hi @beskelton, glad you are finding the package useful. That functionality was deprecated in v1.4 of the Adobe API, which RSiteCatalyst targets. Adobe did not provide replacement functionality. The file you are referencing is marked `internal` in the header; I keep it in the package, just in case Adobe were to bring it back, since it is (theoretically) working code.

**Comment by beskelton** [comment]
Sorry to not notice that, thanks for the prompt reply.
