### ISSUE TITLE
Curl Error

### ISSUE THREAD

**Issue by sreekrishnadutta** [randyzwitch/RSiteCatalyst#168]
Hi,

I was trying to sign into SiteCatalyst through SCAuth, but for some unknown reason, I am not able to. I tried to install RSiteCatalyst as zip specified by you in the code notes, and I have also tried this code, 'install.packages("RSiteCatalyst", lib = "/path/Documents/RSiteCatalyst.zip")', but nothing seems to work. I always get the same error message when I try the authentication. Error message is, "Error in curl::curl_fetch_memory(url, handle = handle) : 
  Couldn't resolve host name" Is there a fix for this? I don't understand why I always end up getting this error. I have loaded all the required libraries. Please help!

**Comment by randyzwitch** [comment]
I'm guessing you're using a Windows machine?

In general, curl errors aren't an RSiteCatalyst problem per se, but really the underlying libraries I import (specifically `httr`). These errors tend to be system-specific, so there isn't a whole lot I can recommend.

What I would suggest is that you try running the same code from a different computer (personal instead of work) or different network (home instead of work) and see if the errors persist. On a personal computer on a personal network, most people find they can connect to the Adobe API. If that's the case for you, then you need to figure out whether your company's network or your company laptop is having the SSL issues.

Good luck.

**Comment by gilliganondata** [comment]
@sreekrishnadutta Any chance you ever got this resolved? I've just hit a case where two different people (me being one of them) are getting this error across: 2 different Adobe apps, 2 different accounts (and companies), and 2 different OSs (one Mac, one Windows). Any chance you found a solution in your case?

**Comment by gilliganondata** [comment]
@sreekrishnadutta I think this might have gotten fixed with the same update that addressed https://github.com/randyzwitch/RSiteCatalyst/pull/224?

**Comment by Misterresearch** [comment]
This did the trick for me...I got me out of my company's firewall. I was tired of using my own machine,

set_config(use_proxy(url="proxy.domain.com",port=8080))

http://stackoverflow.link/question/39285570/error-in-curlcurl-fetch-memoryurl-handle-handle-couldnt-connect-to-ser
