### ISSUE TITLE
Q:When I tried to pull a queuetrended  report, the segments always not work

### ISSUE THREAD

**Issue by xueting1993** [randyzwitch/RSiteCatalyst#170]
data<-QueueTrended(reportsuite.id=rs,
                   date.from = "2016-06-28",
                   date.to = "2016-07-23",
                   metrics=c("visits")
                   ,date.granularity = 'day'
                   ,elements = 'prop51'
                   ,selected = 'dealer:cjdr:us:tier3'
                   ,segment.id<- c("s931_5796f1a0e4b0db4be53f3ca5","55232d57e4b0442b0899a385","5523f599e4b0442b0899a4ba")
)

That's a part of my code, the data can be pulled but the segments didn't been applied and i didn't receive any error message.
I tried to change one of the segment id to wrong, R returned a error message that the segment is invalid. So it seems the segments will be used in the function, but why it doesn't work?

**Comment by randyzwitch** [comment]
This appears to be a syntax error to me, as you are using the assignment operator `<-` instead of `=` for the `segment.id` keyword argument.

Try switching the arrow to equals and see if that fixes it.

```R
data<-QueueTrended(reportsuite.id=rs,
date.from = "2016-06-28",
date.to = "2016-07-23",
metrics=c("visits")
,date.granularity = 'day'
,elements = 'prop51'
,selected = 'dealer:cjdr🇺🇸tier3'
,segment.id<- c("s931_5796f1a0e4b0db4be53f3ca5","55232d57e4b0442b0899a385","5523f599e4b0442b0899a4ba")
)
```

**Comment by xueting1993** [comment]
Yes it works. thank you very much!@randyzwitch  
But why the '<-' cannot used here?  It just assign the segment.id globally , why it matters?

**Comment by randyzwitch** [comment]
Great, glad that fixed it!

The arrow vs. equals thing is a weird R edge case. As I understand it, using the arrow inside a function is just an assignment, so you create an object `segment.id` inside the function call, you don't call the argument. Because I wrote RSiteCatalyst to not require segments, the package code specifies an empty segment unless you re-assgn the keyword value of segment.id. 

So basically, always use an equals sign for assignment and keyword values and you should be fine. Note, you could've also done this if you wanted to make your code more generic to the segments:

```R

segment.id <- c("s931_5796f1a0e4b0db4be53f3ca5","55232d57e4b0442b0899a385","5523f599e4b0442b0899a4ba")

data<-QueueTrended(reportsuite.id=rs,
date.from = "2016-06-28",
date.to = "2016-07-23",
metrics=c("visits")
,date.granularity = 'day'
,elements = 'prop51'
,selected = 'dealer:cjdr🇺🇸tier3'
,segment.id = segment.id
)
```
