### ISSUE TITLE
Q: Can we pull purchaseid via the library?

### ISSUE THREAD

**Issue by datanerd10** [randyzwitch/RSiteCatalyst#171]
Hi @randyzwitch , 
I want to pull omniture data at purchaseID level. Can we get purchaseid as an element via RSitecatalyst library? I tried GetElements but I do not see purchaseID in there. Is there any other place I should be looking for this? Note that we do not capture the purchase ID explicitly in an evar.

**Comment by randyzwitch** [comment]
Unfortunately, I don't know. This blog post suggests that exposing the purchaseid was suggested at one time, but I can't login to see what the status actually is.

http://analyticsdemystified.com/general/validating-orders-revenue/

And as you say, you aren't saving the purchaseid in an eVar, which the blog post also suggests.

I'll leave this open for a few days so that others can comment. If you figure it out, please respond back here so future people searching for this will have an answer.

**Comment by WillemAmbiata** [comment]
It doesn't look like it's available:
https://marketing.adobe.com/developer/documentation/analytics-reporting-1-4/elements

I suspect Adobe consider that the API isn't the place to return granular data, and as such, they don't expose it.

It is available through the data warehouse functionality – is that an option?

**Comment by WillemPaling** [comment]
It doesn't look like it's available:
https://marketing.adobe.com/developer/documentation/analytics-reporting-1-4/elements

I suspect Adobe consider that the API isn't the place to return granular data, and as such, they don't expose it.

It is available through the data warehouse functionality – is that an option?

**Comment by datanerd10** [comment]
Thanks @randyzwitch  and @WillemPaling. I had similar findings but wanted to double-check I wasn't missing out anything. So it look like the purchaseID isn't exposed in Omniture. 

My only option is to use the data warehouse functionality within Omniture, send data to ftp and have a script pick it up from there to load in a database table. This is a good makeshift solution but I lose the ability to manipulate the data before storing, but that's quite alright. 

Thanks again!
