### ISSUE TITLE
DISTINCT COUNT of element values?

### ISSUE THREAD

**Issue by mikehanley** [randyzwitch/RSiteCatalyst#186]
Hey Randy,

I have an element that I need to report on, it contains a list of customer cookie IDs, there can be as many as 50,000 unique IDs per day.

There is already a metric that counts the customer cookies, however it counts the instances, so each distinct ID could have 1 or more instances.

I am trying to do something similar to a SELECT COUNT DISTINCT element_name GROUP BY date, but using Rsitecatalyst.

I am currently using workspace within adobe analytics and getting the row count of the element, by day, but this is slow and cumbersome.

Regards,

Michael

**Comment by randyzwitch** [comment]
Thanks for posting it here, I understand now.

The short answer here is that if it's not possible in the Adobe Analytics interface, then it isn't available from RSiteCatalyst. However, you can probably hack your way around this using some additional R code. I'll probably write a blog post about this, but in the meantime, here are the steps:

1. A `QueueRanked` report is de-duplicated by value, so in effect it represents a `distinct` operation across the time period of the report. Pulling the report  by day using RSiteCatalyst, will give you the distinct count for the day irrespective of the metric used (instances, visits, etc.) 
2.  The Adobe API will return up to 50,000 rows in a given request. This is specified using the `top` and `start` keyword arguments. If you KNOW that it's less than 50,000, then you don't have to worry about paging over the results. If you cannot be sure, then you'll need to do multiple `QueueRanked` requests
3. When you do the `QueueRanked` call, RSiteCatalyst will actually return the cookie id values, so you'll need to do an `nrows` function call in R in order to get the count. You probably want to do this count, assign a date/count value to a dataframe, then delete the dataframe with the actual ids. Of course, this depends on how much RAM you have whether you can keep the raw cookie ids.

Finally, because you'll loop over the days, this will take a long time unless you use the batch/retrieve functionality. The example below should give you enough code to get you through most of these steps:

http://randyzwitch.com/rsitecatalyst-bulk-download-version-1-4-9-release-notes/

Let me know how it goes for you. Like I said, I'll probably write up this example at some point, but it likely won't be today.

**Comment by slin30** [comment]
In case it helps, here's what I've been doing to get e.g. the distinct count of search terms by time, also using QueueRanked, with a calculated metric as outlined here: 

http://www.digitaldatatactics.com/index.php/2016/05/31/find-the-total-number-of-values-in-an-adobe-analytics-variable-report/

Let's assume you've created the metric in your suite, and called it "NROWS":

1. Create a sequence of times. If day, this is easy, as you simply use e.g.  
`seq(as.Date("YOUR_START_DATE"), as.Date("YOUR_END_DATE"), by = "day")`
2. Loop over your sequence of times using QueueRanked, e.g. 
```r
myDays <- seq(as.Date("2016-09-01"), as.Date("2016-09-30"), by = "day")
lst_nq    <- as.list(seq_along(myDays))
for(i in seq_along(lst_nq)) {
mesage("Enqueueing ", i, " of ", length(myDays)
lst_nq[[i]] <- QueueRanked(
reportsuite.id = "RSID", 
date.from = myDays[[i]], 
date.to = myDays[[i]], 
metrics = c("searches", "NROWS"),
elements = "searchterm", 
top = 1, 
segment.id = "MYSEGMENT", 
enqueueOnly = TRUE, 
interval.seconds = 1)
}
```
... Pull data down, etc. 


The key points are:  
- QueueRanked
- Single element/non-nested
- top = 1 since more than one will just be duplicated for the 'NROWS' metric you are interested in
- A metric in addition to 'NROWS', can be anything non-calculated

As an example of the output I just got; name == search term (the top term for the corresponding date), made generic for public sharing :

```
date    name searches NROWS
 1: 2016-09-01  term 1       31  3245
 2: 2016-09-02  term 2       19  2777
 3: 2016-09-03  term 3        6   958
 4: 2016-09-04  term 4       23  1289
 5: 2016-09-05  term 5       25  2279
 6: 2016-09-06  term 6       31  3889
```

You can/should validate by e.g. running a QueueRanked report for a few records, setting `start` and/or `top` as appropriate to ensure that you indeed get the number of rows NROWS suggest you should. For example, I just ran a QueueRanked for 2016-09-03 with top = 10000, same elements and segment.id, and received a report with 958 rows (in my case, 958 search terms). 

I've not had any luck in figuring out a more elegant workflow. I pretty much need one call per time frame per distinct count of whatever element I am interested in. If you have any luck coming up with a better solution than *n* queries for *n* time frames, I'd love to hear about it! As it stands, if I have 30 time ranges and want distinct count of *some_element* for each of say 3 customer segments (for each time range), that's 3*30 calls.
