### ISSUE TITLE
Cancel Report Function returning with error each time.

### ISSUE THREAD

**Issue by shreyasmokadam** [randyzwitch/RSiteCatalyst#222]
Cancel report function of this package, when used with any report id from the Queue with the status 'waiting' doesn't work. 

> CancelReport(1453035286)
[1] "ERROR:  - "
> 

No Further Error code or error message is present. 
The queue has to be processed completely in case of incorrect reports getting queued.

@randyzwitch

**Comment by shreyasmokadam** [comment]
Unable to Cancel reports queued by Mistake. and the API gets Clogged up. 
Any suggestions, Anyone?

**Comment by randyzwitch** [comment]
If the CancelReport method stopped working, Adobe must've changed something about the API call. It's likely a simple fix, but not something important enough for me to fix immediately. I would gladly accept a pull request for a fix, should anyone be interested in contributing back to the package.

**Comment by slin30** [comment]
Followed up on this today since a set of long-running reports were killing one of my report suites. Apparently, the 1.4 version is broken but on Adobe's radar for fixing. In the meantime, Adobe support suggests using the 1.3 method. 

See forum thread: https://forums.adobe.com/thread/2377303

Looking at the older versions of this package, I re-used functionality from https://github.com/randyzwitch/RSiteCatalyst/commit/8b363b145889fb538cce5da3c10b075efbecc8de#diff-aaa28ac6976263fc18719a559aa4d2abR22 and threw together a quick 1.3 workaround, in case anyone else finds it helpful:

```r
old.cancelReport <- function(id) {
  endpoint <- "https://api.omniture.com/admin/1.3/rest/"
  func.name = "Report.CancelReport"
  URL <- paste(endpoint, "?method=",func.name, "&debug=1", sep="")
  
  id <- as.integer(id)
  body <- list(reportID = jsonlite::unbox(id))
  body <- jsonlite::toJSON(body)
  
  ret <- httr::POST(URL,
                    add_headers(BuildHeader()), 
                    body = body
  )
  
  out <- FALSE
  if(ret$status == 200) {
    out <- TRUE
  } 
  
out
}
```

**Comment by randyzwitch** [comment]
Thanks for the follow-up @slin30 and the work-around! Since this is on Adobe's end, I'm not going to push any fix through RSiteCatalyst, but it's great there is a workable R solution.

Closing this, but others feel free to comment to continue the discussion
