### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by XoliloX** [randyzwitch/RSiteCatalyst#229]
Dear Randy,

I got your code with QueuePathing that makes sankey charts working (thanks a lot for this one!). I just have a few questions and I assume you can help me:

- Could you help me read the output in terms of dataframe ? I don't really see how I can connect the dots as when step.1 = entered the website and when step.1 = page name... I am a bit confused regarding this.
- In order to filter for specific path (entered through that page for example), would you recommend to be specific in the pathpattern <- c("::anything::", "::anything::") or should I approach this differently ?
- Count is exactly the number of times a path occurred correct ?

In advance, thanks a lot for your answer !!!
D.

**Comment by randyzwitch** [comment]
> Could you help me read the output in terms of dataframe ? I don't really see how I can connect the dots as when step.1 = entered the website and when step.1 = page name... I am a bit confused regarding this.

Because the example is measuring every 2-step path, the first step can either be that you enter the site or you were on the site and then moved to another page. If you wanted to exclude the `entered site` group, you could.

> In order to filter for specific path (entered through that page for example), would you recommend to be specific in the pathpattern <- c("::anything::", "::anything::") or should I approach this differently ?

Yes, if you wanted to create a report similar to the Adobe interface where one page was the start or endpoint, you could specify the pattern with the exact page name for one of the arguments.

> Count is exactly the number of times a path occurred correct ?

Yes

**Comment by XoliloX** [comment]
Thank you very much Randy !!
Cheers !
