### ISSUE TITLE
QueueDataWarehouse - returned data parsed incorrectly

### ISSUE THREAD

**Issue by j450h1** [randyzwitch/RSiteCatalyst#243]
I noticed that certain columns such as **Date** are returning nonsensical results . My hunch is the data is being parsed incorrectly. Please advise on any tips I can do to troubleshoot?

```
VISIT <- QueueDataWarehouse(
  reportsuite.id = RSID,
  date.from = START,
  date.to = END,
  metrics = c("pageviews","event2","event3"),
  elements = c("evar40","page","mobiledevicetype","visitnumber"),
  date.granularity = "day",
  segment.id = SEGMENT.VISITOR,
  expedite = FALSE,
  max.attempts = 5000,
  enqueueOnly = FALSE
)
```

Here is what some of these non-sensical results look like for the **Date** column:

```
[424]  2018,02411977161379998944053753248939040640,",Other,1,0,1,0\nApril 21                                                                                                            
 [425]  2018,02455111226931449874073525223470141851,mktg:programs:degree-programs,Mobile Phone,1,1,0,0\nApril 21                                                                         
 [426]  2018,02604176995658954680198037310863067069,mktg:admissions:transfer_information,Other,1,3,0,0\nApril 21                                                                         
 [427]  2018,02718529515127738033743647198784646912,mktg:healthcare,Other,6,3,0,0\nApril 21
```
I'm querying 3 months of data and getting back over 3 million records (not that it should make a difference), but its strange because a different report returned back completely fine.

Maybe it has to do something with the fact that there are extra non-escaped commas (or whatever delimiter is used) in the data and its being parsed incorrectly?

**Comment by randyzwitch** [comment]
Within QueueDataWarehouse (and almost all of the functions to be honest), I rely on the default behaviors from the `jsonlite` package, which returns a data.frame when it infers that it the file type is csv.

However, what this implies is that when iterating over a huge amount of data, you can possibly get odd results, as `jsonlite` might choose a different column encoding for each 50k rows in chunks over. Because csv returned via the API doesn't provide types, there isn't much I can do in terms of inferring what the types might be.

Closing this as `wontfix`, if only because I don't think its fixable. My recommendation if you are downloading gigantic amounts of rows would be to use actual DataWarehouse and pick the files up from an SFTP somewhere. This is the only way you can be assured that you can set the types that make sense for your query.
