### ISSUE TITLE
QueueDataWarehouse is converting characters to integers

### ISSUE THREAD

**Issue by cguwilliams** [randyzwitch/RSiteCatalyst#244]
I have ID columns in my data that are comprised of character strings. Sometimes they are pulled correctly, and sometimes I get return values that are all random integers. I'm assuming these integers are conversions of the character values to integers at some point in the function.

Whether or not the characters are converted to integers seems to depend on the order in which I enter my evars in the function, and not all character variables are converted to integers. Some come in as factors, some as characters, and some as integers. 

I'm assuming there's some implicit conversion going on. If there were a way to just have all variables come in as factors, that would be a huge step toward fixing this issue.

**Comment by randyzwitch** [comment]
See https://github.com/randyzwitch/RSiteCatalyst/issues/243

In general, there is no custom parsing code in RSiteCatalyst, I rely on the default behavior from `jsonlite`. Adobe returning data as a CSV in this way is always going to be error-prone and to be honest, there's not a lot I can do about it. Because every implementation is different, building custom logic to parse every edge case people might have isn't feasible.

My recommendation if you need to use DataWarehouse is to pick the data up from an SFTP, so that you can clean your data and set the types properly.
