### ISSUE TITLE
Interrupting function leads to later errors

### ISSUE THREAD

**Issue by randyzwitch** [randyzwitch/RSiteCatalyst#49]
Ran this function call; didn't seem like it was going to resolve after 50+ tries

``` R
queue_trended_top10pages_daily <- QueueTrended("report suite",
                                               "2013-01-01",
                                               "2014-01-28",
                                               "pageviews",
                                               "page",
                                               top="10",
                                               date.granularity =  "day")

```

After interrupting the code, trying to run the code again led to the following error:

``` R
 Error in function (type, msg, asError = TRUE)  : 
  easy handled already used in multi handle 

```

@WillemPaling, have you ever seen anything like this? This feels like a new error, I've never had any issues killing a function then re-running it.

**Comment by Luckyscharms2000** [comment]
Hello Everyone,

I know this is long since closed, but if there's any information on it or how to work around it I would appreciate it - I'm getting the same error when running a QueueRanked report- 

Error in JsonQueueReport(toJSON(report.description)) : 
  ERROR: the API validated the report, but did not return a report ID

**Comment by randyzwitch** [comment]
Unfortunately, I don't know what the issue is, as it's difficult to reproduce. The best advice I can give is to use the most recent version of httr, as the error seemed to disappear when we did that during development.
